### ISSUE TITLE
For clarity, add a .map and .flatMap for decoders

### ISSUE THREAD

**Issue by mrmurphy** [mlms13/bs-decode#23]
You clued me in on mapping the result of a decoded function in Discord, and I should have thought of that myself. But I think adding map and flatMap to the decoder library would be helpful. You mentioned that you wanted to, so I'm making an issue for it!

**Comment by andywhite37** [comment]
@mlms13 - while you're doing this, you should see if it makes sense to make `Decoder` an apply/applicative too, because that might unlock some additional type-classy stuff from bs-abstract.

**Comment by mlms13** [comment]
Yeah, I think my strategy for this is going to be adding `Functor`, `Apply`, `Applicative`, and `Monad` implementations for the `Js.Json.t => M.t('a)` type inside `DecodeBase`, then we can just expose `map`, `flatMap`, and possibly `apply` for each `Decode` module. I'm not sure what a `pure` function looks like in this case... maybe `let pure = (v, _json) => v`?

Anyway, I probably won't get to this for a couple days, so if anyone else wants to take a stab at it...
