### ISSUE TITLE
Expose type for `Nel`?

### ISSUE THREAD

**Issue by mrmurphy** [mlms13/bs-decode#24]
I don't have the non-empty list library added to my project, so I discovered that I can't explicitly type the return type of a decoder function.

It'd be nice either to expose the non-empty list type, for explicit typing, or maybe to expose a type-alias for `Decode.resultOfStringNelDecoder('a)` or something like that. What do you think?

**Comment by mlms13** [comment]
I'm switching from `bs-nonempty` to `relude`'s `NonEmptyList` implementation internally. It should be a pretty seamless switch to the outside world, in terms of functionality, and as part of this, I'll add a `Decode.NonEmptyList.t('a)` type+module to the interface files.

I'll also expose `map`, `foldLeft`, `head`, `tail`, and maybe a couple other helper functions so you can do something useful with the value you get out of the Error, without needing to explicitly add other libraries.

**Comment by mlms13** [comment]
This is done in the branch I just pushed. I hope to merge that to master and make a release in the next day or so.
