### ISSUE TITLE
Alias "base" decoders in the Pipeline module

### ISSUE THREAD

**Issue by mlms13** [mlms13/bs-decode#27]
This is mostly to allow for easier local opens, e.g.:

```re
let decode = json =>
  Decode.AsResult.OfParseError.Pipeline.(
    succeed(make)
    |> field("name", string)
    |> field("age", intFromNumber)
    |> run(json)
  );
```

**Comment by mlms13** [comment]
@phated I think you initially mentioned this to me, which may have been part of the reason we changed `float` to `floatFromNumber` (for better local opening). Any interest in taking this one?

**Comment by phated** [comment]
@mlms13 yeah, I did mention it.  I tried tackling it and ran into a bunch of issues because I don't understand the infix operators.  The reason I am using Pipeline is because I don't understand them 😦

**Comment by mlms13** [comment]
Ok, no worries, I can take a stab at this. I also want to make our use of infix operators more consistent (or possibly more minimal) internally. There are places where we're using `|> map(...)` and places where we `<#>`. Consistency should make this more approachable.
