### ISSUE TITLE
NonEmptyList usage

### ISSUE THREAD

**Issue by phated** [mlms13/bs-decode#28]
I saw some new issues/suggestions that mentioned NonEmptyList and it made me remember that working with `oneOf` is clumsy because it must be constructed with a NonEmptyList (which means the end-user has to install it as a top-level dependency, etc).  Could methods that expect a `NonEmptyList` take a normal list and internally construct the NonEmptyList?  I think it'd make the ergonomics nicer.

**Comment by mlms13** [comment]
Yeah, I forget the exact API for that one, but it seems like requiring `(first, rest)` instead of `(nonEmptyList)` is probably the way to go here. :+1:

**Comment by mlms13** [comment]
I'm cleaning up some `NonEmptyList` stuff, and I'm planning to make `oneOf` no longer depend on it.

**Comment by mlms13** [comment]
This is done in the `reludify` branch... should be released as 0.5.0 in a day or two.
