### ISSUE TITLE
`fallback` is only for fields?

### ISSUE THREAD

**Issue by mlms13** [mlms13/bs-decode#29]
This feels awkward, to the point I'm going to avoid documenting `fallback` for now. It seems like if you want to use fallback with a field, you should just `D.fallback(D.field("foo", D.string), "default", json)`. That way you could also use `fallback` in combination with any simple JSON value as well.

I'm not quite sure how this will affect the Pipeline module, which has its own version of fallback.

**Comment by phated** [comment]
I was just using `fallback` and had the same thought!  I think it'd be fine to have the pipeline usage be the same as you suggested above.

**Comment by mlms13** [comment]
I just pushed a change that makes `fallback` work for any decoder. You can achieve the old behavior with `Decode.(fallback(field("x", string), "default value"))`.

This new `fallback` is aliased inside of `Decode.Pipeline`, but the old behavior still exists as `fallbackField`, which is often what you'll want for pipeline decodes. This is similar to `optional` vs `optionalField`, so I think it makes sense?
