### ISSUE TITLE
Fix `toDebugString`

### ISSUE THREAD

**Issue by mlms13** [mlms13/bs-decode#5]
I think it's pretty close, but...

- [x] Make a version that can be called with only the error
- [x] Make an example that takes advantage of the extensible nature of `DecodeBase.failure`
- [ ] Mention this in the readme

**Comment by shinzui** [comment]
Could you please give me an example of using the current version of `toDebugString` before you resolve this issue?

**Comment by shinzui** [comment]
Are you planning any API changes to the Result of ParseError API?

**Comment by mlms13** [comment]
This is documented in the `docs` branch, which will absolutely 100% be going into `master` today and will be released as part of 0.4.
