### ISSUE TITLE
Allow named arguments in record constructors

### ISSUE THREAD

**Issue by austindd** [mlms13/bs-decode#58]
First of all, I'm really loving this library. It's been extremely useful for several projects I'm working on. So thanks for putting in the time to build this!

I just wanted to suggest a potential enhancement. When constructing large records of data, it can be cumbersome and error-prone to pass 20+ arguments to that constructor, especially when half of them are just `string` or `bool` types, so I often use named arguments to alleviate that issue a bit.

It would be nice if I could pass that same `make` function into a decoder pipeline without any errors. As it stands, I need to duplicate the `make` function with the arguments left unnamed, and use that for decoding.

It's not a huge issue at all, more of a 'nice-to-have' feature. But I also don't know if this is actually feasible or even possible at all. I'd be interested to hear your thoughts on that.

**Comment by mlms13** [comment]
At the moment, I don't _think_ it's possible to use labels, since both the `Pipeline` approach and the `<$>`/`<*>` approach are based on partial application where order of application is significant. I agree that this is not ideal and potentially a source of errors with big `make` functions, but I'm not sure what can be done about it.

However, with the upcoming `let+`/`and+`/`let*` feature, I think it should be possible to leverage the `Apply` nature of decoders and write something like this (warning, I don't actually know the right syntax):

```reason
open Decode.AsResult.OfParseError;
let decode = json => {
  let+ firstName = field("first_name", string, json)
  and+ lastName = field("last_name", string, json)
  and+ email = field("email", string, json)
  and+ birthday = field("birthday", date, json);
  make(~firstName, ~lastName, ~email, ~birthday);
};
```

**Comment by austindd** [comment]
Ah, I see... Well, all the more reason get excited about those upcoming features!

**Comment by mlms13** [comment]
I pushed a branch where I started playing around with this, and it _seems_ to be working as well as expected. This depends on a Bucklescript PR, and I haven't yet tested some of the more complex cases (error collection, applicative mixed with monadic `flatMap`, etc), but I expect that stuff to work out pretty well.

If you're interested in trying it out, the branch is `letops`, and here's a fairly complex example with mutually-recursive decoders: https://github.com/mlms13/bs-decode/blob/letops/test/Decode_AsOption_test.re#L504-L524

**Comment by mlms13** [comment]
Sadly, the Bucklescript PR that this depended on got closed unresolved, and some leaders from the Reason community made it pretty clear that they don't plan to support this kind of abstraction in the future. We can re-address this in the future if the situation changes, but with the current leadership, that seems quite unlikely.
