### ISSUE TITLE
Needs bs-abstract upgrade

### ISSUE THREAD

**Issue by mlms13** [mlms13/bs-decode#59]
Just a little note-to-self that `bs-decode` is another project that can't be compiled with the latest `bs-platform` until `bs-abstract` make a release resolving the empty array issue.

**Comment by flash-gordon** [comment]
@mlms13 mind to push a release? I'm depending on the master branch atm, everything works fine.

**Comment by mlms13** [comment]
Thanks for the ping! I think I had to run and catch a bus after pushing the last change, and then I forgot to release it. :)

**Comment by mlms13** [comment]
v0.10.0 is out with updated dependencies and BuckleScript 7.1 compatibility.

I pushed one more breaking change before making the release, but it's only a break if you're using `Decode.ParseError.ResultOf` to extend the error type with custom errors, and all you have to do to get around the break is delete `.Monad` when constructing `DecodeBase` with a result module.

**Comment by flash-gordon** [comment]
Thank you!
