### ISSUE TITLE
mention bs-bastet as a peer dependency over bs-abstract in the docs

### ISSUE THREAD

**Issue by hamza0867** [mlms13/bs-decode#61]
As you can see in the picture below, the doc still mentions using bs-abstract as a peer dependency
![Screenshot from 2020-04-12 15-19-04](https://user-images.githubusercontent.com/38878982/79071001-145efd00-7cd1-11ea-82f4-bda44975a8e6.png)

But when I ran `yarn install bs-decode`, yarn told me bs-decode needs a peer dependency called `bs-bastet`

I believe the docs need a small upgrade in this regard

Thank you guys for the amazing work you put on this library

**Comment by mlms13** [comment]
Good catch! I think I updated the actual doc files, but I probably haven't run the website build. I'll take a look right now.

**Comment by mlms13** [comment]
Website should be up to date now, after a hard refresh, and I updated the README as well.
