### ISSUE TITLE
bs-decode no longer compiles v0.11.1

### ISSUE THREAD

**Issue by hamza0867** [mlms13/bs-decode#65]
Hello guys,

Thank you for this amazing library. I just want to point out that bs-decode no longer compiles under bs-platform 7.3.2 or 8.0.2.

I believe the problem comes from [this line](https://github.com/mlms13/bs-decode/blob/master/bsconfig.json#L13).

[Here](https://github.com/hamza0867/bs-decode-compilation-error/tree/master) is a reproducible repo. 

Instructions to reproduce the error and a possible fix are in the repo.

**Comment by hamza0867** [comment]
Should there be a new release 0.11.2 that fixes this issue. I believe it is kind of blocking. I will be more than happy to help in any way I can.

**Comment by mlms13** [comment]
Done
