### ISSUE TITLE
Add `oneOf` to try multiple decoders

### ISSUE THREAD

**Issue by mlms13** [mlms13/bs-decode#7]
```reason
module D = Decode.AsResult.OfParseError;
type foobar = Foo(FooModule.t) | Bar(BarModule.t);

let decodeFoo = json => FooModule.decode(json) |> D.ResultUtil.map(v => Foo(v));
let decodeBar = json => BarModule.decode(json) |> D.ResultUtil.map(v => Bar(v));

let decodeFoobar = json =>
  D.oneOf([ decodeFoo, decodeBar ], json);
```

Internally, `oneOf` should probably be defined in terms of alt (`<|>`). The list of decoders will all need to return the same success type `'a`. `oneOf` should try the list of decoders in order and return the first `Ok`. If all decoders fail, return the last `Error` is probably fine, although it might be neat to collect the errors in a structured way.

**Comment by mlms13** [comment]
Alternatively, the lib user could extend `ParseError` with their own errors, and then they could handle the `oneOf` error however they want.

```reason
module R = Decode.ParseError.ResultOf({
  type t = [ DecodeBase.failure | `InvalidFoobar(Js.Json.t) ];
  let handle = x => (x :> t);
});

module D = DecodeBase.DecodeBase(R.TransformError, R.Monad, R.Alt);

let decodeFoobar = json =>
  D.oneOf([ decodeFoo, decodeBar ], json) |> R.mapErr(_ => `InvalidFoobar(json));
```

**Comment by mlms13** [comment]
Additionally, I think `oneOf` should expect a `NonEmptyList` of decode functions to try. I'm not sure what `let myResult = D.oneOf([], json)` should even do. Feels like we should prevent that at compile time, especially since `NonEmpty` is already a dependency of `bs-decode`.

Here's a quick shot at an implementation:

```reason
let rec oneOf = (fns, json) =>
  BsAbstract.List.Foldable.fold_left(
    (result, fn) => result <|> fn(json),
    NonEmptyList.head(fns)(json),
    NonEmptyList.tail(fns)
  );
```

**Comment by phated** [comment]
I'm planning to replace bs-json in my project but I'd need `oneOf`

**Comment by mlms13** [comment]
`master` now has a working version of `oneOf` (and even a couple tests to prove it), but it if you decode into a `Result.t`, the current implementation of `oneOf` is only tracking the last failure instead of collecting the failures from all of the decoders that were tried. I'll try to fix that in the next day or two, and then I'll make a new release.

**Comment by mlms13** [comment]
I'm going to call this done, since `oneOf` exists and is working. I've opened a new ticket (#26) to address how we should handle multiple attempts that all fail.
